### ISSUE TITLE
怎么用？

### ISSUE THREAD

**Issue by donson** [LinFeng1997/vuepress-plugin-export-site#1]
如题

**Comment by LinFeng1997** [comment]
https://vuepress.vuejs.org/zh/plugin/using-a-plugin.html#%E4%BD%BF%E7%94%A8%E6%9D%A5%E8%87%AA%E4%BE%9D%E8%B5%96%E7%9A%84%E6%8F%92%E4%BB%B6 @donson d 需要在 vuepress 1.0.0-alpha8 以上的版本使用此插件

**Comment by donson** [comment]
> https://vuepress.vuejs.org/zh/plugin/using-a-plugin.html#%E4%BD%BF%E7%94%A8%E6%9D%A5%E8%87%AA%E4%BE%9D%E8%B5%96%E7%9A%84%E6%8F%92%E4%BB%B6 @donson d 需要在 vuepress 1.0.0-alpha8 以上的版本使用此插件

好的，可以用了

**Comment by donson** [comment]
> https://vuepress.vuejs.org/zh/plugin/using-a-plugin.html#%E4%BD%BF%E7%94%A8%E6%9D%A5%E8%87%AA%E4%BE%9D%E8%B5%96%E7%9A%84%E6%8F%92%E4%BB%B6 @donson d 需要在 vuepress 1.0.0-alpha8 以上的版本使用此插件

怎么调整页面顺序？

**Comment by LinFeng1997** [comment]
@donson 目前还不支持自定义 pages

**Comment by LinFeng1997** [comment]
@donson 增加了 pageReorganization 参数用来自定义 pages
